// Add new property to filter configs to be used in label
export const CONTROL_NAME_LABELS = {
  HD: 'Hougang Depot',
  AMKD: 'Ang Mo Kio Depot',
  ARDD: 'Aver Raja Depot Depot',
  depot: 'Depot',
  depots: 'Depot Name',
  depotsSec: 'Depots',
  effectiveDate: 'Effective Date',
  effectiveDateDAGWLive: 'Effective Date (DAGW Live)',
  effectiveDateDAGWTrial: 'Effective Date (DAGW Trial)',
  eventDateTime: 'Event Date Time',
  consistency: 'Consistency',
  active: 'Active Parameter',
  mdcsAccess: 'MDCS Access',
  type: 'Type',
  trialGroup: 'Application Trial Group',
  busServiceGroup: 'Bus Service Group',
  fareParameterGroup: ' Fare Parameter Group',
  userId: 'User ID',
  date: 'Date',

  // Bus Monitoring
  connection: 'Connection Status',
  download: 'Parameter Download Status',
  upload: 'Parameter Upload Status',
  auth: 'SAM Auth Status',
  // Bus Transfer
  currDepot: 'Current Depot',
  currOperator: 'Current Operator',
  futureOperator: 'Future Operator',
  //bus list
  dayType: 'Day Type',
  serviceNo: 'Service No.',
  busId: 'Bus ID',
  // vehicle map
  status: 'Status',
  // Report
  reportType: 'Report Type',
  businessDate: 'Business Date',
  monthType: 'Month Type',
  serviceProvider: 'Service Provider Name',
  startDate: 'Start Date',
  endDate: 'End Date',
  spName: 'SP Name',
  // Maintenance
  currDate: 'Current Business Day',
  eodExecuted: 'Last EOD Executed',
  updateType: 'Update Type',
  //Parameter Viewer
  iMaxUsers: 'Number of User Access entries',
  aobjBusFleet: 'Bus Fleet',
  aobjUserAccess: 'User Access',
  UAD: 'Access Display',
  // BCV_CFGB.SYS - BCV Configuration - isMultiVersion, isTriable, isLocationSpecific
  aobjBCVSpecificConfig: 'BCV Configuration',
  iNumOfEntries: 'Number of Entries',
  iSystemOwnerID: 'System Owner ID',
  iStartOfOprDay: 'Start of Operation Day',
  iCSCRejectTimeout: 'Same CSC Reject Timeout (milliseconds)',
  iCardDetectTimeout: 'Card Detection Timeout',
  iInServiceRevenueARUploadInterval:
    'In-Service Revenue Audit Register Periodic snapshot interval (minutes)',
  iNonRevenueARUploadInterval:
    'Non-Revenue(Out of Service) Audit Register Periodic snapshot interval (minutes)',
  iReadFailureControlNumberOfFailures:
    'CSC Read Failure Control - Number of Failures',
  iReadFailureControlSampleSize: 'CSC Read Failure Control - Sample Size',
  iWriteFailureControlNumberOfFailures:
    'CSC Write Failure Control - Number of Failures',
  iWriteFailureControlSampleSize: 'CSC Write Failure Control - Sample Size',
  iAntiPassbackTimeout: 'Anti - Passback timeout (seconds)',
  iPatronMsgTimeout: 'Patron message timeout (milliseconds)',
  iSwitchOutOfService: 'Switch to Out Of Service',
  iTimeDrift: 'Clock Drift Error Limit (minutes)',
  iCancelTime: 'Cancel Time (minutes)',
  iBreakdownTransferTime: 'Breakdown Transfer Time (minutes)',
  iEntryProcessTimeout: 'Entry Processing Timeout (seconds)',
  iMsgFlushInactivityTimer: 'Message Flush Inactivity Timer (seconds)',
  iBFCHeartbeatInterval: 'BFC Heartbeat interval',
  iBLSHeartbeatInterval: 'BLS Heartbeat interval',
  iEnquiryReadCount: 'Enquiry Read Count',
  iEnquiryDisplayCount: 'Enquiry Display Count',
  iPrematureEndOfTripFreeRide: 'Premature End of Trip free ride',
  iSpecialModeInactivityTimeout: 'Special Mode Inactivity Timeout (seconds)',
  iAutoAmbientLightAdjustment: 'Auto Ambient Light Adjustment',
  iEntryMismatchExitOption: 'Entry Mismatch at Exit Option',
  iMaxPenaltyAmt: 'Maximum Penalty Amount',
  iMinPenaltyAmt: 'Minimum Penalty Amount',
  iProcessIncompleteCSCWriteTimeout:
    'Process Incomplete CSC Write Timeout (seconds)',
  iMemoryProfileParameterFullLimit: 'Memory Profile - Parameter Full Limit',
  iMemoryProfileMessageFullLimit: 'Memory Profile - Transaction Full Limit',
  // BFC_CBTx.SYS - BFC Specific Configuration By Bus TypeId - isMultiVersion, isTriable, isLocationSpecific
  aobjBFCSpecificConfig: 'BFC Configuration',
  BID: 'BID',
  SOID: 'System Owner ID',
  SOD: 'Start of Operation Day',
  PFL: 'Memory Profile - Parameter Full Limit',
  MFL: 'Memory Profile - Message Full Limit',
  DKBDB: 'Default Kbd Backlight',
  DAS: 'Default AirCon Status',
  POT: 'Power Off Time',
  SITL: 'Short Inactivity Time Limit',
  LITL: 'Long Inactivity Time Limit',
  MDT: 'Message Display Time',
  QLB: 'Qty LED Blinks',
  LEDBT: 'LED Blink Time',
  CDEL: 'Clock Drift Error Limit (minutes)',
  OBDCT: 'On Bus Device Connection Time',
  OffDCT: 'Off Bus Device Connection Time',
  FMSHT: 'FMS Heartbeat Time',
  FMSMRET: 'FMS Message Reply Error Timeout',
  BCVHT: 'BCV Heartbeat Time',
  BCVMRET: 'BCV Message Reply Error Timeout',
  BCV1M: 'BCV 1 Mode',
  BCV2M: 'BCV 2 Mode',
  BCV3M: 'BCV 3 Mode',
  BCV4M: 'BCV 4 Mode',
  BCV5M: 'BCV 5 Mode',
  BCV6M: 'BCV 6 Mode',
  QHT: 'QTA Heartbeat Time',
  QMRET: 'QTA Message Reply Error Timeout',
  BLSAAE: 'BLS Auto Activate Enabled',
  BLSLCE: 'BLS Location Correction Enabled',
  BLSCE: 'BLS Control Enabled',
  CRPCRE: 'CRP Cash Recording Enabled',
  CRPCT: 'CRP Cancel Timeout',
  PINRS: 'PIN Required Supervisor',
  PINRM: 'PIN Required Maintainer',
  PINRD: 'PIN Required Driver',
  PINRMCSC: 'PIN Required Master CSC',
  PINEL: 'PIN Entry Limit',
  PINLT: 'PIN Lockout Time',
  SM: 'Supervisor Modes',
  MM: 'Maintainer Modes',
  IM: 'Inspector Modes',
  DM: 'Driver Modes',
  MCSCM: 'Master CSC Modes',
  DOUE: 'Driver Odometer Update Enabled',
  DSSE: 'Driver Service Select Enabled',
  OTARUI: 'On-Trip Audit Register Periodic Upload interval (minutes)',
  OffTARUI: 'Off-Trip Audit Register Periodic Upload Interval',
  CLEDOT: 'Concession Icon On Time',
  IOE: 'Interchange Ops Enabled',
  NOfSBT: 'Show X Bad Transactions',
  CRE: 'Card Retention Enabled',
  AETE: 'Auto End Trip Enabled',
  SURT: 'Stop Update Remind Timeout',
  CPMT: 'Check Point Mode Timeout',
  AAA: 'Auto Ambient Light Adjustment',
  C1KT: 'Concession 1 Key Concession Type',
  C2KT: 'Concession 2 Key Concession Type',
  C3KT: 'Concession 3 Key Concession Type',
  C4KT: 'Concession 4 Key Concession Type',
  C5KT: 'Concession 5 Key Concession Type',
  T1KV: 'Top-up 1 Key Value',
  T2KV: 'Top-up 2 Key Value',
  T3KV: 'Top-up 3 Key Value',
  T4KV: 'Top-up 4 Key Value',
  T5KV: 'Top-up 5 Key Value',
  PEPT: 'Premature Exit Processing Type',
  CTE: 'Complimentary Tickets Enabled',
  DSLE: 'Device Secure Load Enabled',
  AUFS: 'Application Upgrade File Size',
  DTSIT: 'DTS Inactivity Timeout',
  SIDF: 'Security ID Flag',
  aBDR: 'BDR',
  BRC: 'Blacklist Reason',
  BSCID: 'BSC ID',
  BR: 'BR',
  // BLS1CFGA - BLS1 Configuration - isMultiVersion, isTriable, isLocationSpecific
  aobjBLS1SpecificConfig: 'BLS1 Configuration',
  iRevisionID: 'Revision ID',
  iCommTimeout: 'Communications timeout value',
  iODOInFrontErrLimit: 'Odo in front error limit',
  iODOTowardsErrLimit: 'Odo towards error limit',
  iLocationFlags: 'Location flags',
  iGPSErrorTimeout: 'GPS error timeout',
  iGPSTimeDiffToUTC: 'GPS time difference to UTC',
  iHDOPLimit: 'Hdop limit',
  iCosinePHI: 'Cosine phi',
  iGPSFlags: 'GPS flags',
  iExpectedErrorOfGPS: 'Expected Error of GPS',
  iAgeOfDGPSData: 'Age of DGPS data',
  iSlowSpeedTripPt: 'Slow Speed trip at',
  iSlowSpeedHystValue: 'Slow Speed hyst val',
  iLocReportCycDistance: 'Location report cyc distance',
  iLocReportCycTime: 'Location report cyc time',
  iODOMeterFaultLimit: 'Odometer fault limit',
  iGYROMeterFaultLimit: 'Gyrometer fault limit',
  iHeartBeatTime: 'Heartbeat time',
  iRadiusOfCertainity: 'Radius of certainty',
  iProximityDistance: 'Proximity distance',
  iSpeedReportingTime: 'Speed Reporting Time',
  iSpeedChangeTheshold: 'Speed Change Threshold',
  iMarkerOvershootTheshold: 'Marker Overshoot Threshold',
  iOffRouteAlarmReportTime: 'Off-route Alarm Report Time',
  iTemperatureTheshold: 'Temperature Threshold',
  iVoltageTheshold: 'Voltage Threshold',
  iCurrentTheshold: 'Current Threshold',
  iOffRouteDistTheshold: 'Off-route Distance Threshold',
  // GCM_PDTA - GCM Parameter Description Table - null, null, null //SeP_PDTX.XXX //SeP_PDTX.SYS
  aobjPDTDetails: 'Parameter Description Table',
  iNumFiles: 'Number of Files',
  strParameterMsgType: 'Message Type',
  iServiceProviderID: 'Service Provider ID',
  iDepotID: 'Depot ID',
  iFileID: 'File ID',
  iVersion: 'Parameter Version',
  strFileName: 'Parameter Name',
  strPath: 'Parameter Path',
  //ABT_BBRX.SYS
  aobjCardBlacklistRange: 'Card Blacklist Range',
  // ABT_EWLA - null, null, null
  aobjBSD: 'Bank Card Schemes',
  aobjWED: 'Bank Card Whitelist',
  NBSD: 'Number of Bank Schemes entries',
  NED: 'Number of Whitelist entries',
  HVER: 'Hashed PAN Key Version',
  AID: 'Bank Scheme AID',
  WCHK: 'Whitelist Check',
  ESTDT: 'Eff. Start Date',
  EEDDT: 'Eff. End Date',
  HPN: 'PAN Hash',
  // ABT_FDXX
  strTFBPD: 'Target Full Blacklist Ref. Date',
  TFBPVer: 'Target Full Blacklist Parameter Version',
  strRFBPD: 'Reference Full Blacklist Ref. Date',
  RFBPVer: 'Reference Full Blacklist Version',
  //ABT_TDDX.SYS
  iFullBlacklistParamVersion: 'Full BL Ver',
  strRefDate: 'Ref. Date',
  iNoOfAddedBlacklistEntries: 'Blacklist Entries Added',
  aobjAddedBlackList: 'Blacklist To Add',
  iNoOfRemovedBlacklistEntries: 'Blacklist Entries Removed',
  aobjRemovedBlackList: 'Blacklist To Remove',
  //ABT_TFDX.SYS
  NEC: 'Number of Card Entries',
  NER: 'Number of Card Range Entries',
  //BLS2CBTX.SYS
  aobjBLS2SpecificConfig: 'BLS2 Specific Configuration',
  RID: 'Revision ID',
  BODOMCF: 'Base ODO Meter Con Factor',
  HODOMCF: 'High ODO Meter Con Factor',
  LODOMCF: 'Low ODO Meter Con Factor',
  GPSRP: 'GPS Receiver Position',
  NOfD: 'Number Of Doors',
  OnFT: 'On Filter Time',
  OffFT: 'Off Filter Time',
  DOS: 'Door Open Signal',
  AODOMCL: 'Actual ODO Meter Con Limit',
  RSP: 'Reverse Signal Polarity',

  //BUS_BATX.SYS
  iMaxBlacklistActionDefinition: 'Max Blacklist Action Definition',
  aobjBlacklistAction: 'Bus Blacklist',
  strBitCardBadDebtRefAction: 'Bad Debt Reference',
  strBitCardBlockAction: 'Disable Purse',
  strBitCardRejectAction: 'Reject Card',
  strBbitCardDisableAutoloadAction: 'Disable AutoLoad',
  strBitCardRetainAction: 'Retain Card',
  strBitCardReplaceAction: 'Replace Card',
  strBitCardRefundImmediateAction: 'Refund Card Immediately',
  strBitCardDeferRefundAction: 'Deferred Refund Card',
  strBitCardCollectPenaltyAction: 'Collect Penalty',
  strBitCardRefuseAutoloadAction: 'Refuse AutoLoad',
  strBitCardBadDebtSettleAction: 'Settle Bad Debt Allowed',
  strBitCardRFU: 'RFU',

  //BUS_CSFX.SYS
  aobjBusCashFare: 'Bus Cash Fare',
  iBusCashFareDef: ' Bus Cash Fare Def',
  iServiceCategory: 'Service Category',
  iAdultIDFCButton1FareAmount: 'Adult IDFC Btn No.1 Fare',
  iAdultIDFCButton2FareAmount: 'Adult IDFC Btn No.2 Fare',
  iAdultIDFCButton3FareAmount: 'Adult IDFC Btn No.3 Fare',
  iAdultIDFCButton4FareAmount: 'Adult IDFC Btn No.4 Fare',
  iAdultIDFCButton5FareAmount: 'Adult IDFC Btn No.5 Fare',
  iAdultIDFCButton6FareAmount: 'Adult IDFC Btn No.6 Fare',
  iAdultIDFCButton7FareAmount: 'Adult IDFC Btn No.7 Fare',
  iAdultIDFCButton8FareAmount: 'Adult IDFC Btn No.8 Fare',
  iChildIDFCButton1FareAmount: 'Child IDFC Btn No.1 Fare',
  iChildIDFCButton2FareAmount: 'Child IDFC Btn No.3 Fare',
  iChildIDFCButton3FareAmount: 'Child IDFC Btn No.3 Fare',
  iSeniorCitizenIDFCButton1FareAmount: 'Senior IDFC Btn No.1 Fare',
  iSeniorCitizenIDFCButton2FareAmount: 'Senior IDFC Btn No.2 Fare',
  iSeniorCitizenIDFCButton3FareAmount: 'Senior IDFC Btn No.3 Fare',

  //BUS_DSTX.SYS
  NEDE: 'Number of Entry',
  NExDE: 'Number of Exit',
  aobjBEDisc: 'Bus Entry Discount',
  DiscID: 'Discount Set ID',
  LSC: 'Last Service Category',
  CSC: 'Current Service Category',
  PC1DA: 'Patron Cat 1 Discount Amt',
  PC2DA: 'Patron Cat 2 Discount Amt',
  PC3DA: 'Patron Cat 3 Discount Amt',
  PC4DA: 'Patron Cat 4 Discount Amt',
  PC5DA: 'Patron Cat 5 Discount Amt',
  PC6DA: 'Patron Cat 6 Discount Amt',
  PC7DA: 'Patron Cat 7 Discount Amt',
  PC8DA: 'Patron Cat 8 Discount Amt',
  PC9DA: 'Patron Cat 9 Discount Amt',
  PC10DA: 'Patron Cat 10 Discount Amt',
  PC11DA: 'Patron Cat 11 Discount Amt',
  PC12DA: 'Patron Cat 12 Discount Amt',
  PC13DA: 'Patron Cat 13 Discount Amt',
  PC14DA: 'Patron Cat 14 Discount Amt',
  PC15DA: 'Patron Cat 15 Discount Amt',
  aobjBExDisc: 'Bus Exit Discount',
  SC: 'Service Category',
  SS: 'Start Stage',
  ES: 'End Stage',

  //BUS_FBCX.SYS
  aobjBusFareBandToCashFareMap: 'Cash Fare Band',
  iFareBandID: 'Fare Band ID',
  iAdultFareButtonID: 'Adult Cash Fare Band Code',
  iChildCashFareBandCode: 'Child/Student Cash Fare Band Code',
  iSeniorCitzCashFareBandCode: 'Senior Citizen Cash Fare Band Code',

  //BUS_FPTX.SYS
  aobjTransitUsageGenParam: 'Transit Usage General',
  iParamSwitchOverDate: 'Switch Over Date',
  iMaxNumberOfTransfers: 'Max Number of Transfers',
  iMaxJourneyTime: 'Max Journey Time',
  iMaxTransferTimeExitPerformed: 'Max Transfer Time if Exit Performed',
  iMaxTransferTimeExitNotPerformed: 'Max Transfer Time if Exit Not Performed',
  iMaxTimeInRailSystem: 'Max Time in Rail System',
  iDistanceChargedSameEntryExit:
    'Distance Chargeable for Same Bus Stop of Entry-Exit',
  iMaxTransferTimeRailtoRail: 'Max Transfer Time for Rail to Rail Transfer',
  iMaxTransferTimeIntraTownBus:
    'Max Transfer Time for Intra-Town Feeder Bus Service Transfer',
  aobjTicketCategoryMap: 'Ticket Category Map',
  iDefaultTicketCategory: 'Default Ticket Category',
  iFareCapPeriodType: 'Fare Cap Period Type',
  strBusFareCapAmt: 'Bus Fare Cap Amount',
  strRailFareCapAmt: 'Rail Fare Cap Amount',
  strBusAndRailFareCapAmt: 'Bus & Rail Fare Cap Amount',
  strOffPeakBusAndRailFareCapAmt: 'Off Peak Fare Cap Amount',
  strZeroFareServiceProvider: 'Zero Fare Service Provider',
  aobjPatronCatMap: 'Patron Category Map',
  aobjWeekdayTimeTable: 'Weekday Timetable',
  aobjSaturdayTimeTable: 'Saturday Timetable',
  aobjSundayOrPHTimeTable: 'Sunday or Public Holiday Timetable',
  iOffPeakPassTimingIndicator: 'Off Peak Pass Time Indicator',
  iStartOfTimePeriod: 'Start Time Period',
  iEndOfTimePeriod: 'End Time Period',
  iTC1: 'TC 1',
  iTC2: 'TC 2',
  iTC3: 'TC 3',
  iTC4: 'TC 4',
  iTC5: 'TC 5',
  iTC6: 'TC 6',
  iTC7: 'TC 7',
  iTC8: 'TC 8',
  iTC9: 'TC 9',
  iTC10: 'TC 10',
  iTC11: 'TC 11',
  iTC12: 'TC 12',
  iTC13: 'TC 13',
  iTC14: 'TC 14',
  iTC15: 'TC 15',

  //BUS_PSFX.SYS
  aobjBusPremiumServiceFare: 'Bus Premium Service Fare',
  iPremiumServiceFareDef: 'Premium Service Fare Def',
  iPatronCategory1FareAmount: 'Patron Cat 1 Fare',
  iPatronCategory2FareAmount: 'Patron Cat 2 Fare',
  iPatronCategory3FareAmount: 'Patron Cat 3 Fare',
  iPatronCategory4FareAmount: 'Patron Cat 4 Fare',
  iPatronCategory5FareAmount: 'Patron Cat 5 Fare',
  iPatronCategory6FareAmount: 'Patron Cat 6 Fare',
  iPatronCategory7FareAmount: 'Patron Cat 7 Fare',
  iPatronCategory8FareAmount: 'Patron Cat 8 Fare',
  iPatronCategory9FareAmount: 'Patron Cat 9 Fare',
  iPatronCategory10FareAmount: 'Patron Cat 10 Fare',
  iPatronCategory11FareAmount: 'Patron Cat 11 Fare',
  iPatronCategory12FareAmount: 'Patron Cat 12 Fare',
  iPatronCategory13FareAmount: 'Patron Cat 13 Fare',
  iPatronCategory14FareAmount: 'Patron Cat 14 Fare',
  iPatronCategory15FareAmount: 'Patron Cat 15 Fare',

  //BUS_SVTX.SYS
  NBG: 'Number of Bus Group',
  BG: 'Bus Group',

  //BUS_UATX.SYS
  SID: 'User/Staff ID',

  //DCS_BLPX.DUP //DCS_BLRX.DUP //DCS_BLSX.DUP //DCS_BLWX.DUP
  iNumberOfBusListRecords: 'Number of Bus List entries',
  aobjBusListDetails: 'Bus List Details',
  strBusNumber: 'Bus Number',
  strDepotID: 'Depot ID',
  strBusParkID: 'Bus Park ID',
  strAssignedSvcNumber: 'Assigned Service Number',
  strExpectedTimeOfReturn: 'Expected Time Of Return',
  iExpectedNumberOfCatridges: 'Expected Number Of Catridges',

  //DCS_CFGX.SYS
  aobjDCSConfig: 'DCS Configurations',
  BackupDuration: 'Backup Duration',

  //DCS_FLTA.SYS
  NE: 'Number of Entries',
  BRN: 'Bus Register No',
  BGID: 'Bus Group ID',
  BTID: 'Bus Type ID',

  //IDFCBSDB.SYS
  aobjBusStop: 'Bus Stop',
  BSID: 'Bus Stop ID',
  BSD: 'Bus Stop Description',

  //IDFCCKAB.SYS
  aobjCashKeyAssignment: 'Cash Key Assignment',
  strServiceCategoryName: 'Service Category',
  iCashFareButtonSet: 'Cash Fare Btn Set',

  //IDFCVLMX.SYS
  aobjVLSMarker: 'VLS Marker',
  iMarkerID: 'Marker ID',
  iStopRadius: 'Bus Stop Radius Val',
  iLatitude: 'Latitude Val',
  iLongitude: 'Longitude Val',

  //IPD_CFGX.SYS
  aobjIPDSpecificConfig: 'IPD Configurations',
  iARUploadInterval: 'Audit Register Periodic Snapshot Interval (minutes)',
  iDefaultBacklight: 'Default LCD Backlight',
  iPINEntries: 'PIN retries',
  iDataFileRetentionPeriod: 'Data File Retention Period',
  iPenaltyFixedAmt: 'Fixed Penalty Indicator',
  iPenalty: 'Fixed Penalty Amount ($)',

  //MDCSMBLX.SYS
  NMBLR: 'Number of Master Bus List Records',
  aobjMBLD: 'Master Bus List',
  BN: 'Bus Number',
  SPID: 'Service Provider ID',
  EDT: 'Effective Date Time',
  DBM: 'Depot Bit Map',

  //MDCSTDLA.XXX
  iNoOfTrialBusListRecords: 'Number of Trial Device List',
  aobjTrialBusListDetails: 'Trial Device List',
  iGroupBitMap: 'Group Bit Map',

  //MDCSUATA.SYS
  SP: 'Service Provider',
  LTAUser: 'LTA User',
  ALS: 'Account Locked',
  PED: 'Password Expiry Date',

  //SeP_BUTX.SYS
  NICEDef: 'Number of Individual Card Entries',
  NICREDef: 'Number of Individual Card Entries',
  aobjBU: '',
  aobjICE: 'Individual Card Entry',
  CAN: 'Card Application Number',
  BDC: 'Bad Debt Counter',
  aobjICRE: 'Card Range Entry',
  CANS: 'Card Application Number - Start',
  CANE: 'Card Application Number - End',

  //SeP_DBBX.SYS
  iNoOfAddedEntriesDef: 'Number of Added entries',
  iNoOfRemovedEntriesDef: 'Number of Removed entries',
  iHashPanKeyVersion: 'Hashed PAN Key Version',
  iFullBlocklistParamVersion: 'Full Blocklist Version',
  aobjBlocklistAddedEntryDef: 'Blocklist Added Entry',
  strHashPan: 'PAN Hash',
  strBlockListReason: 'Blocklist Reason',
  aobjBlocklistRemovedEntryDef: 'Blocklist Removed Entry',

  //SeP_FBBX.SYS
  iNoOfEntries: 'Number of Entries',
  aobjBankCardFullBlocklistDetails: 'Bank Card Full Blocklist',

  //SeP_ISSX.SYS
  usiNumCardManager: 'Number Card Manager',
  aobjCardManager: 'Card Manager',
  iNumIssuerIDsDefined: 'Number Issuer IDs Defined',
  aobjIssuerID: 'Issuer ID',
  strIssuerID: 'Issuer ID',

  //SeP_PBHX.SYS
  aobjPublicHoliday: 'Public Holiday',
  strDate: 'Public Holiday Date',

  //SeP_SGPX.SYS
  aobjGeneralSystemDefParam: 'System General',
  iStandardTktLifeValidPerdiod: 'Standard Ticket Life Validity Period (days)',
  iOffsetTimeForPeakStartTime: 'Offset Time for Peak Start Time (minutes)',
  iOffsetTimeForPeakEndTime: 'Offset Time for Peak End Time (minutes)',
  iABTAntiPassbackTime: 'ABT Anti Passback Time (minutes)',
  iCBTAACardUsageRejectionStartDate:
    'CBT AA Card Usage Rejection Start Date (days)',
  aobjTransitCardTypes: 'Transit Card Types',
  iTransitCardTypeCode: 'Transit Card Type Code',
  iTransitCardType: 'Transit Card Type Valid Ind',
  aobjOperatorAssignments: 'Operator Assignments',
  iParticipantID: 'Participant ID',
  aobjTicketProfileDef: 'Ticket Profile Definition',
  iTicketTypeCode: 'Ticket Type Code',
  iTktTypeValidityInd: 'Ticket Valid Indicator',
  iConcessionCode: 'Concession Code',
  iTktType2Availability: 'Ticket Type 2 Availability',
  iEnExSequenceCheck: 'Entry/Exit Sequence Check Indicator',
  iExcessTimeInCheck: 'Excess Time in System Check Indicator',
  iLowPurseBalance: 'Low Purse Balance',
  iRailMinEntryVal: 'Rail Minimum Travel Value',
  strTktTypeName: 'Ticket Type Name',
  strTktTypeAbbr: 'Ticket Type Abbreviation',
  strServiceCategoryBitmap: 'Service Category Bitmap',
  aobjPassProfileDef: 'Pass Profile Definition',
  iPassTypeCode: 'Pass Type Code',
  iValidTktType: 'Valid Ticket Type Code',
  iDailyOrCumulativeUsage: 'Daily Use Indicator',
  iOffPeakPassInd: 'Off Peak Pass Indicator',
  iRailUsageLimit: 'Rail Usage Limit',
  iBusUsageLimit: 'Bus Usage Limit',
  strPassTypeName: 'Pass Type Name',
  aobjFareCapDef: 'Fare Cap Definition',
  iCheckFCOptInIndicator: 'Check Fare Cap Opt-in',
  iEnableFCOptInOption: 'Enable Fare Cap Opt-in',
  strFareCapServiceCategoryMap: 'Fare Cap to Svce Category Map',

  //SeP_TVWX.SYS
  aobjTeVWhitelistDetails: 'TeV Whitelist',
  strCAN: 'Card ID',
  iTeVID: 'TeV ID',
  strPayoutAmt: 'Payment Amount',
  strPayoutExpiryDate: 'Payout Expiry Date',
  strPayoutType: 'Payout Type',

  //USGEBAMA.SYS
  iNoOfEMVBlockListActionMsgs: 'Number of EMV Blocklist',
  aobjEMVBlockListActionMsgs: 'EMV',
  strBlocklistReason: 'Blocklist Reason',
  strBlocklistPatronActionMsg: 'Patron Action Message',
  bitAllowRailExit: 'Allow Bus Exit',
  bitRFU: 'RFU',
  iNoOfCEPASBlockListActionMsgs: 'Number of CEPAS Blocklist',
  aobjCEPASBlockListActionMsgs: 'CePAS TOKEN',
  bitDisableTokenAction: 'Disable Token',
  bitRejectTokenAction: 'Reject Token',
  bitRetainTokenAction: 'Retain Token',
  bitAllowDebtSettlementAction: 'Allow Debt Settlement',
  bitAllowRailExitAction: 'Allow Bus Exit',
  bitAllowTopUpAction: 'Allow Top-Up',

  //SVT
  SN: 'Service Number',
  ACC: 'Air Con Service Category',
  NACC: 'Non Air Con Service Category',
  ACG: 'Air Con Service Grade',
  NACG: 'Non Air Con Service Grade',
  TFI: 'Through-Fair Indicator',
  SSID: 'Special Service ID',
  IF: 'Feeder Indicator',
  NMD1: 'Number of Outbound Entries',
  NMD2: 'Number of Inbound Entries',
  NV: 'Number of Variants',
  ESFC: 'Entry Stepdown-Fare Charge',
  UCS: 'Use Checkpoint Stage',
  UBS: 'Use By-pass Stages',
  MI: 'Marker ID',
  TBP: 'Trunk By-pass',
  ST: 'Stop Type',
  NM: 'Type and Distance',
  DFO: 'Distance from Origin',
  VD: 'Variant Descriptor',
  VID: 'ITS Variant ID',
  VSPID: 'Service Provider',
  VPID: 'Package ID',
} as const;
